name: Post Trump Tweet

on:
  # Schedule: 9am, 12pm, 3pm, 6pm, 9pm EST = 2pm, 5pm, 8pm, 11pm, 2am UTC
  schedule:
    - cron: '0 14,17,20,23,2 * * *'  # 5 times per day
  
  # Allow manual triggers for testing
  workflow_dispatch:

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Post tweet
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NODE_ENV: production
          TIMEZONE: America/New_York
        run: npm start
      
      - name: Commit state changes
        run: |
          git config user.name "Trump Bot"
          git config user.email "bot@github.com"
          git add data/state.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update bot state [skip ci]" && git push)
        continue-on-error: true


